[package]
name = "bridgestan"
version = "1.0.0"
edition = "2021"

[dependencies]
nuts-rs = { version = "0.4.0", optional = true }
thiserror = "1.0.37"

[build-dependencies]
bindgen = "0.60.1"

[features]
nuts = ["dep:nuts-rs"]

[[example]]
name = "nuts"
required-features = ["nuts"]
