[bridgestan]
git-tree-sha1 = "ac3a3214a3759f4eb652ce30f2e1b2feb6df1f00"
lazy = true

    [[bridgestan.download]]
    sha256 = "6eb3526b831fc81bd4283169e38ad54bf0cf91ebc5a527862212fbd6b8fe603e"
    url = "https://github.com/roualdes/bridgestan/releases/download/v2.1.1/bridgestan-2.1.1.tar.gz"
